### ISSUE TITLE
Is actions-executing supposed to work with feature modules?

### ISSUE THREAD

**Issue by jfai** [ngxs-labs/actions-executing#11]
I refactored an app so that some of the actions are now in feature modules (one is loaded lazily, one is not).  In the feature modules, NgxsModule is imported using forFeature.
The subscription to the actionsExecuting observable is done in the bootstrap root component of the app.
After refactoring, the subscription no longer triggers. Before the refactoring, all was working as expected.

**Comment by joaqcid** [comment]
@jfai there might be a timing issue in your scenario, `actionsExecuting` will start listening after it was registered with `NgxsActionsExecutingModule.forRoot()`.

If the action you are selecting is dispatched before NgxsActionsExecutingModule is registered, you might not get the expected behaviour.

If you need more help with your scenario, please create a stackblitz with the repro case to take a look.

Thanks!

**Comment by jfai** [comment]
Figured it out after looking at the implementation. After changing the order of imports of  NgxsModule.forRoot() and NgxsActionsExecutingModule.forRoot(), all is good again. Thanks for the hint.
